FROM node:18.16.0-alpine3.17 AS builder

WORKDIR /usr/src/app
COPY . .

RUN yarn install && yarn build

FROM node:18.16.0-alpine3.17 AS deploy

ENV NODE_ENV development
ENV TZ=Asia/Seoul

RUN apk --no-cache add tzdata && \
   cp /usr/share/zoneinfo/$TZ /etc/localtime && \
   echo $TZ > /etc/timezone \
   apk del tzdata

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app ./

RUN apk add --no-cache --update bash

RUN chmod +x ./wait-for-it.sh